### ISSUE TITLE
Swap Mouse control

### ISSUE THREAD

**Issue by matthewjporter** [PiotrMachowski/Home-Assistant-Taskbar-Menu#4]
Hi There

Great App and looks realy nice and seems to work very well

I do have a comment on the way tyou interact with the taskbar Icon. Normally double left click opens the app (what ever app that may be) and a right click brings up the icon/app menu

Your app seems to be the otherway round - Is this configurable?

Regards

**Comment by PiotrMachowski** [comment]
Hi!

Menu was original main functionality of this app, so it opens on left click. Webview was added as an additional one, so right now it uses right click.

Configurability might be an option, I will check it out

**Comment by matthewjporter** [comment]
Cheers, Thats makes sense since you had no use for it before the web interface was added

If you need any testing drop me a line

**Comment by noxhirsch** [comment]
I also think left click for web interface and right click for menu makes more sense, because that's how most taskbar applications work. I always click wrong :D 
So a setting for that would be amazing.
Additionally (to make it behave more consistant to other software) it would be great, if a second click on the taskbar icon closes the web view.

**Comment by PiotrMachowski** [comment]
I think I will have to swap click behavior, I also quite frequently use wrong mouse button :)

**Comment by PiotrMachowski** [comment]
I have swapped functions of mouse buttons in v1.1.2.0
